### ISSUE TITLE
Numeritos y estadísticas

### ISSUE THREAD

**Issue by sergiovier** [SIU-Toba/framework#11]
Podemos dejar mas lindo esto, si le agregamos estadísticas de descargas vía packagist, datos de la versión, etc. Está genial este [servicio](https://poser.pugx.org/), ej: [![Total Downloads](https://poser.pugx.org/siu-toba/framework/downloads)](https://packagist.org/packages/siu-toba/framework)

**Comment by enfoqueNativo** [comment]
Como le pifie en el nro de ticket dejo aca el hash [8769acb45c1764543c76164303d7b372ca918c5b]
