### ISSUE TITLE
En toba_usuarios cuando se integra con Araí, se rompe las consultas rest

### ISSUE THREAD

**Issue by sergiovier** [SIU-Toba/framework#14]
Al parecer, se está [utilizando](https://github.com/SIU-Toba/framework/blob/develop/proyectos/toba_usuarios/php/lib/rest_arai_usuarios.php#L95) los métodos Guzzle de la versión 5, para consumir los rest. 

Con que se lo modifique y se reemplace `json`() por `getBody`() estaría funcionando.

**Comment by sergiovier** [comment]
Bueno, haciendo pruebas, efectivamente se mete en el camino `rest_decode`. Algún detalle se me está escapando, si lo haces directo con json_decode funciona pero le falta la conversión obligada a latin1.

**Comment by enfoqueNativo** [comment]
Creo que la manera seria reemplazarlo por esto
`$datos = rest_decode($response->getBody()->__toString());`

Lo tengo en stage porque no estoy pudiendo probarlo con Araí para verifficar que no explota por otro lado.

**Comment by enfoqueNativo** [comment]
Done @[09b905191f58b5fa865ebc36ea063b2b7125145c]
