### ISSUE TITLE
Cuando la configuración full_url contiene una barra al final, rompe SSO vía Araí

### ISSUE THREAD

**Issue by sergiovier** [SIU-Toba/framework#15]
En el `instancia.ini` hoy se regsitra en `full_url` la url del proyecto. Si se configura mal, entra una `/` al final nos deja mal configurado la plataforma Araí... y por ende el acceso vía SSO de dicha aplicación junto con su API. Podríamos modificar el [hook](https://github.com/SIU-Toba/framework/blob/develop/src/SIUToba/Arai/RegistryHooksProyectoToba.php#L410) para que lo evite.

**Comment by enfoqueNativo** [comment]
El Hook esta modificado, ahora solo hay que asegurarse que sea consistente el registro de la url, tanto full como parcial, siempre deberia tener una / al final (para estar en concordancia con lo recomendado por Apache)

**Comment by sergiovier** [comment]
Fixed in https://github.com/SIU-Toba/framework/commit/4c77a32bac4f42cba3c16326b6b4761162d0fe3d
