### ISSUE TITLE
Modificador abstract no admitido en función generar de la interface toba_vista_xslfo_callback_generacion

### ISSUE THREAD

**Issue by pacecf** [SIU-Toba/framework#158]
En la interface toba_vista_xslfo_callback_generacion la función generar esta definida con modificador abstract pero las interfaces no lo requieren.
en
https://github.com/SIU-Toba/framework/blob/develop/php/nucleo/lib/salidas/toba_vista_xslfo_callback_generacion.php#L10

**Comment by enfoqueNativo** [comment]
@pacecf Hola, ahi meti un commit [861cd66](https://github.com/SIU-Toba/framework/commit/861cd664c708205f296e5b402d2be7806c611ef1) corrigiendo este problema. 

Busque en otros archivos por si se repetia el inconveniente pero no encontre la combinacion.
De curioso nomas, te salto con alguna version especifica de PHP este error?.

Gracias por el aviso :)
