### ISSUE TITLE
toba_vista_jasperreports deja las conexiones abiertas

### ISSUE THREAD

**Issue by enfoqueNativo** [SIU-Toba/framework#160]
Al usar la vista jasperreports e inyectar una conexión de bd al reporte, si algo falla durante la ejecucion y se sale por una excepcion pueden quedar abiertas las conexiones JDBC y por ende la ejecucion del SERVLET queda zombie.

**Comment by sergiovier** [comment]
v3.4 o v3.3.x como hotfix?

**Comment by enfoqueNativo** [comment]
> v3.4 o v3.3.x como hotfix?

Sale como hotfix, quedo 3.4 por costumbre al armar el issue. Ahi lo cambio
