### ISSUE TITLE
Bug de compatibilidad de método en toba_logger_ws::log

### ISSUE THREAD

**Issue by rdsmiranda** [SIU-Toba/framework#170]
Al intentar instanciar la consola swagger con Toba 3.4.0

`PHP Fatal error:  Declaration of toba_logger_ws::log($level, Stringable|string $message, array $context = []) must be compatible with Psr\\Log\\AbstractLogger::log($level, Stringable|string $message, array $context = []): void in ../vendor/siu-toba/framework/php/nucleo/lib/toba_logger_ws.php on line 57, referer: http://localhost/../swagger/index.html?url=http://localhost/../rest/api-docs`

**Comment by enfoqueNativo** [comment]
Fix @[78033b386], @rdsmiranda confirmame

**Comment by rdsmiranda** [comment]
De 10 @enfoqueNativo! Gracias :)
