### ISSUE TITLE
BUG: No se puede configurar autenticación rest por variable de entorno

### ISSUE THREAD

**Issue by dcandotti** [SIU-Toba/framework#177]
La autenticación rest permite el seteo de una variable de entorno (API_BASIC_CLIENTES) para evitar el uso de archivos de configuración pero dicha funcionalidad no está funcionando correctamente. El problema está en el archivo [php/nucleo/lib/rest/toba_usuarios_rest_conf.php](https://github.com/SIU-Toba/framework/blob/develop/php/nucleo/lib/rest/toba_usuarios_rest_conf.php) en la línea [90](https://github.com/SIU-Toba/framework/blob/4bc65c120f54b60d58f2c2579aefd30ed800fca6/php/nucleo/lib/rest/toba_usuarios_rest_conf.php#L90). Después de parsear el valor de la variable de entorno, la contraseña se setea en un array usando la clave 'password' pero un par líneas más arriba (línea [72](https://github.com/SIU-Toba/framework/blob/4bc65c120f54b60d58f2c2579aefd30ed800fca6/php/nucleo/lib/rest/toba_usuarios_rest_conf.php#L72)) se intenta leer dicha contraseña usando la clave 'api_key'.

**Comment by enfoqueNativo** [comment]
@dcandotti En ningun lugar dice que dicha variable se utilice para lo que pretendes, en todo caso lo que falta es un mecanismo similar para poder cargar `API_KEYS` via variables de entorno.
