### ISSUE TITLE
Error en Siu Toba 3.4 insert_masivo

### ISSUE THREAD

**Issue by delucagaston** [SIU-Toba/framework#181]
Log error:  Warning: Undefined variable $elementos in vendor/siu-toba/framework/php/lib/db/toba_db_postgres7.php on line 288
count(): Argument #1 ($value) must be of type Countable|array, null given

Linea de con error 288:
$sql = "-- COPY $tabla FROM stdin de ".count($elementos)." filas.";

Corrección:
$sql = "-- COPY $tabla FROM stdin de ".count($datos)." filas.";

**Comment by enfoqueNativo** [comment]
Relacionado con [180](https://github.com/SIU-Toba/framework/issues/180)
