### ISSUE TITLE
PHPExel fué deprecada

### ISSUE THREAD

**Issue by sergiovier** [SIU-Toba/framework#23]
La librería [PHPExel](https://github.com/PHPOffice/PHPExcel) fué deprecada en diciembre último. No tiene mantenimiento desde el 2015... dan como alternativa pasarse a [PhpSpreadsheet](https://github.com/PHPOffice/PhpSpreadsheet).

**Comment by enfoqueNativo** [comment]
Done @[0c0ae08b8083fba4573470d8f5c4836ba9d2631c]
