### ISSUE TITLE
utilizar PHPMailer 6.x con soporte a namespaces

### ISSUE THREAD

**Issue by sergiovier** [SIU-Toba/framework#24]
La nueva versión tiene soporte a namespaces, es la que está en constante actualización (la versión 5.x ya no tiene mas soporte). Ver [guía](https://github.com/PHPMailer/PHPMailer/blob/master/UPGRADING.md) de migración.

**Comment by enfoqueNativo** [comment]
Done @[151999c97c8fe51b095ab296a6bc7a11d0d4399d]
