### ISSUE TITLE
Generación innecesaria de archivos de logs para WS

### ISSUE THREAD

**Issue by sergiovier** [SIU-Toba/framework#30]
En toba, el logger para los servicios rest parece estar configurado de forma incorrecta. Con sistemas medianamente intensivos en el acceso a sus api rest, tenemos cientos de archivos de logs que nos quedan en `i__<instancia>/p__<aplicacion>/logs/web_services/`.

Tal parece que el inconveniente puede venir por [acá](https://github.com/SIU-Toba/framework/blob/f22e80cb1726f3b79457b30da355102ee939f5e5/php/nucleo/lib/toba_logger_ws.php#L124), por cada ID de solicitud se está generando un archivo.

/cc @enfoqueNativo @andres-blanco

**Comment by sergiovier** [comment]
La opción de desactivarlo por defecto me parece válida. Se está generando mucho output de manera estándar.

Por otro lado, como ves que se tome el camino de mandar todo a un mismo logger (archivo) y formatear la entrada cosa de que contenga el ID de la solicitud? No será fácil de leer para el que mira a mano un log, pero también hoy por hoy los que juegan en serio o tengan un volumen indecente tendrán algo que les permita sistematizarlo.

**Comment by enfoqueNativo** [comment]
> La opción de desactivarlo por defecto me parece válida. Se está generando mucho output de manera estándar.

Es verdad, lo pongo como desactivado para la próxima versión.

> Por otro lado, como ves que se tome el camino de mandar todo a un mismo logger (archivo) y formatear la entrada cosa de que contenga el ID de la solicitud? No será fácil de leer para el que mira a mano un log, pero también hoy por hoy los que juegan en serio o tengan un volumen indecente tendrán algo que les permita sistematizarlo.

Para mandarlo todo a un solo lugar, habría que cambiar el mecanismo de log directamente, onda usar Monolog en todo (incluso Toba).  Como esta hoy, tenerlo todo en un mismo archivo te genera pedidos de pagina cortados (cuando cicla), complicando aun mas el debug. Por otro lado, hay que cambiar la manera en la que trabaja ya que al guardar parcialmente hay que trackear que se guardo y que no, es posible.. pero quizas requiera algo mas integral.

**Comment by hslavich** [comment]
El logger hace un chmod que en directorios con mucha cantidad de logs (+100k) genera tiempos de respuestas muy altos haciendo la api practicamente inaccesible.

https://github.com/SIU-Toba/framework/blob/41255e63c1c9b460cdabcd03b71681eacb0cb207/php/nucleo/lib/toba_logger_ws.php#L115

**Comment by enfoqueNativo** [comment]
> El logger hace un chmod que en directorios con mucha cantidad de logs (+100k) genera tiempos de respuestas muy altos haciendo la api practicamente inaccesible.
> 
> [framework/php/nucleo/lib/toba_logger_ws.php](https://github.com/SIU-Toba/framework/blob/41255e63c1c9b460cdabcd03b71681eacb0cb207/php/nucleo/lib/toba_logger_ws.php#L115)
> 
> Line 115 in [41255e6](/SIU-Toba/framework/commit/41255e63c1c9b460cdabcd03b71681eacb0cb207)
> 
>  			@toba_manejador_archivos::chmod_recursivo($path, $permisos);

Si, por eso se cambia la forma de loguear, se va por un esquema de unico archivo por defecto y posibilidad de explicitar la separación:
 [framework/php/nucleo/lib/toba_logger_ws.php](https://github.com/SIU-Toba/framework/commit/876422d3ae996d2b86f681c5400f1ad2277a1c93#diff-e1e3a84d07806e18cc229743596adb1c)
