### ISSUE TITLE
Advertencia id de desarrollador no configurada

### ISSUE THREAD

**Issue by falvez** [SIU-Toba/framework#35]
Estaría bueno que si se realizo una instalación de un ambiente de desarrollo y no se configuro el id de desarrollador, que al entrar al toba editor muestre una advertencia o algo que el desarrollador se de cuenta que esta por generar metadatos sin un id de desarrollo y con esto evitar conflictos de metadatos mediante la generación involuntaria de metadatos sin id de desarrollo.

**Comment by enfoqueNativo** [comment]
No existe tal cosa como no configurar el id de desarrollo, el valor por defecto '0' es tan valido como cualquier otro. 

No es posible saber el id de todo el grupo que esta desarrolando, si todos colocan 2, 44, 12, o 57 van a tener problemas de la misma forma, aun cuando sean distintos del valor por defecto, el problema por tanto no es el valor, sino que todos usen el mismo.

**Comment by sergiovier** [comment]
@enfoqueNativo Entiendo lo del ID cero, es una feature. Creo que la consulta iba mas orientado a que muchas veces sucede que uno **olvida configurarlo**. En un ambiente colaborativo... hasta que uno no mergea su trabajo con otro remoto, no es fácil enterarse y ya es tarde para llorar.

**Comment by enfoqueNativo** [comment]
Podria agregar algo a la pantalla que avisa del usr/grp de Apache... que tampoco le dan bola :face_with_head_bandage:
