### ISSUE TITLE
Exportación de un cuadro con salida Bootstrap

### ISSUE THREAD

**Issue by rdsmiranda** [SIU-Toba/framework#41]
La exportación básica de un cuadro se rompe porque está generando tags html en el archivo de salida cuando se utiliza el manejador de salida bootstrap.

**Comment by rdsmiranda** [comment]
Perdón, el problema se debe a caracteres especiales en los títulos de los cortes de control.

**Comment by rdsmiranda** [comment]
Vuelvo a molestar, la salida efectivamente se rompe en cuadros con cortes de control.

**Comment by enfoqueNativo** [comment]
[Ticket](https://gitlab.siu.edu.ar/siu/manejador-salida-bootstrap/issues/1) en el repo del proyecto

**Comment by enfoqueNativo** [comment]
@rdsmiranda eso es porque necesitas el [branch](https://github.com/SIU-Toba/framework/tree/feature/updateInterfaceManejador) que tiene los cambios necesarios en el cuadro.

Por otro lado, el update a la version del manejador debio generarte un error, ya que no existe aun la version 1.2 requerida para la interface de manejadores.

**Comment by rdsmiranda** [comment]
Bárbaro. Era para saber si estaban atentos nomás. Los estoy vigilando de cerca xD

**Comment by enfoqueNativo** [comment]
Merged @[9aa6bf03e7b9ff91bc90b22665bf5a2bf915aea7] requiere develop manejador-salida-x por ahora.
