### ISSUE TITLE
Error en los filtros

### ISSUE THREAD

**Issue by lcassettai** [SIU-Toba/framework#47]
![2019-06-19_09-25](https://user-images.githubusercontent.com/12787110/59765381-53b8ea80-9274-11e9-967b-6e4988f66a94.png)

Al hacer click en el boton eliminar en los filtros, no se elimina, y en consola muestra el mensaje que se ve en la imagen.

**Comment by enfoqueNativo** [comment]
Hola @lcassettai,
solucionado en siu/manejador-salida-toba@1.0.2 

Saludos
