### ISSUE TITLE
No se visualiza el boton borrar a nivel fila en los multilinea

### ISSUE THREAD

**Issue by lcassettai** [SIU-Toba/framework#48]
![2019-06-19_09-24](https://user-images.githubusercontent.com/12787110/59765530-aabebf80-9274-11e9-8ddf-7d66e8785ff3.png)

Al tildar la opcion "Botón Borrar - Mostrar en filas " en las opciones del multilinea (en el toba editor) , en vez de mostrar el boton de borrar, coloca la palabra "yo"

**Comment by enfoqueNativo** [comment]
Hola @lcassettai, 
actualiza el paquete siu/manejador-salida-toba@1.0.2 por favor.

Saludos
