### ISSUE TITLE
Soporte al desarrollo con branches

### ISSUE THREAD

**Issue by enfoqueNativo** [SIU-Toba/framework#5]
Toba tiene la forma de manejar los ID de los metadatos construyendolos a partir del id de desarrollador + una secuencia.  Si los proyectos van a utilizar git + flow en algún momento, el uso de branches para desarrollar nuevas features hace que quizá los ID de elementos se repitan entre branches y den conflicto. 

Por ej, partiendo de develop, inicia una feature, crea una operación, luego inicia otra feature y crea una operación.  Esto hace que las dos operaciones tengan el mismo ID y obviamente cuando se mergeen los branches respectivos, entran en conflicto.

@ablanco  propone que se tome un valor "random" que se saque del hash del branch actual, por ej con este comando:

```bash
git show-ref --abbrev=4 `git rev-parse --abbrev-ref HEAD` --heads -s
```

Eso nos da un número en hexa, podemos pasarlo a decimal y formar el id del elemento onda `desarrollador`+  `branch` + `secuencia`. Los campos de postgres parecen ser todos bigint, con 8 bytes de capacidad...

**Comment by enfoqueNativo** [comment]
Resumen de charla (si me olvido de algo agregalo Andrew):

-HASH, propuesta id_desarrollador + timestamp (podriamos agregar proyecto tambien por si las moscas)

Pro: 
*  Solucionaria el problema de los branches y equipos de desarrollo.

Contra: 
*  Problemas para determinacion de metadatos mal comiteados y/o merges. Las tablas M:N se vuelven un parto.
*  Influye en la navegación, el id de operacion pasaria a ser un hash tambien.
*  Necesita cambio masivo en código y todas las tablas (re-fundación).

-IDBranch, propuesta columna extra en bd

Contra:
*  No soluciona inconveniente con secuencias (no se pueden repetir nros, no importa si son clave o no)
*  Requiere modificar todas las tablas + algo de código

-IDBranch, propuesta contador que se adjunta a id_desarrollador, formato id_desarrollador . id_branch

Pro:
*  Mitiga el problema de branches (requiere hook en git para actualizar contador en carpeta instalacion), a nivel global hay que ejercer control estricto en id_desarrollador
*  No toca la estructura, es un cambio a nivel logico.

Contra:
*  El nro de branches es finito, si se sobrepasa nos pasamos al rango de otro desarrollador y hay colisiones.
*  El hook en git podria desperdiciar nros (el switch a develop no vuelve al nro inicial)
*  Solo existen 999 branches con 999 objetos cada uno en el mejor de los casos.
*  Existen tablas con secuencias de tipo CHAR (perdimos apuesta satanica?)

-IDBranch, propuesta contador que se adjunta a id_desarrollador, formato id_branch . id_desarrollador

Pro:
*  Mitiga el problema de branches (requiere hook en git para actualizar contador en carpeta instalacion), no de equipo de desarrollo.
*  No toca la estructura, es un cambio a nivel logico.

Contra:
*  Superposicion con rangos existentes ej:
     id_desarrollador: 14
     id_branch: 1
   Se superpone con
     id_desarrollador: 4
     id_brach: 11

En cualquiera de los casos el Id de desarrollador deja de ser util para identificar a la persona, simplemente se transforma en un separador de rangos medio pelo. Solución definitiva.. HASH, solución de compromiso id_desarrollador + IDBranch.

**Comment by enfoqueNativo** [comment]
Done [48c598be9dbda1caca79a16b467eccbe609778c9] y [bf6189c8dc53fb4b04eabc3042df5ae9f42180b3]. @sergiovier Te animas a beta-testearlo?

**Comment by sergiovier** [comment]
@enfoqueNativo on my way...

La opción `--points-at` de for-each-ref fué introducida al parecer a partir de git 2.7.... Debian 8 todavía utiliza git 2.1 :angry: 

Intento luego con un git de backports o me paso a stretch el finde

**Comment by enfoqueNativo** [comment]
Undo + metodo alternativo, chau hooks.

**Comment by lgraziani2712** [comment]
Hola! Hay algún archivo de documentación, o en su defecto commit o código, donde pueda ver cómo se solucionó?

Estamos pensando en migrar de la 2.6 (con svn), a la 3 (con git) y tengo curiosidad de cómo se resolvió este problema.

Gracias!

**Comment by sergiovier** [comment]
El cambio se implementó en https://github.com/SIU-Toba/framework/commit/a5e3daac719752bad7127dd73dc5308ba4c75f56 y lo que se hace básicamente es crear un archivo `.sequence_list` que almacene los números de secuencia de los metadatos. Como este archivo está almacenado en `/ruta/proyecto/instalacion/i__<instancia>/.sequence_list`, no está bajo el control de versiones y perdura entre los cambios de branches que realicen. 

Con esto se evita las colisiones en los números de secuencias.
