### ISSUE TITLE
Agregar campo en saml.ini

### ISSUE THREAD

**Issue by enfoqueNativo** [SIU-Toba/framework#57]
Agregar la posibilidad en saml_onelogin de forzar el uso de variables X-Forwarded via setProxyVars(true) de acuerdo a un parametro en archivo ini.

**Comment by sergiovier** [comment]
Surge en el caso de que tengamos una app creada con Toba, que autentique vía `saml_onelogin`, se está produciendo un error de validación de la metadata (respuesta que le envía el IDP).

> [Fri Oct 11 08:19:35.876059 2019] [php7:notice] [pid 1929] [client 172.27.3.2:60488] Errores en el proceso de onelogin: , referer: https://idp-test.unx.edu.ar/module.php/arai/loginuserpass.php?
> [Fri Oct 11 08:19:35.876128 2019] [php7:notice] [pid 1929] [client 172.27.3.2:60488] array (\n  0 => 'invalid_response',\n), referer: https://idp-test.unx.edu.ar/module.php/arai/loginuserpass.php?
> [Fri Oct 11 08:19:35.876140 2019] [php7:notice] [pid 1929] [client 172.27.3.2:60488] The response was received at http://usuarios-test.unx.edu.ar/ instead of https://usuarios-test.unx.edu.ar/?acs, referer: https://idp-test.unx.edu.ar/module.php/arai/loginuserpass.php?
> [Fri Oct 11 08:19:35.877171 2019] [php7:notice] [pid 1929] [client 172.27.3.2:60488] toba_error_seguridad: Error Interno Se produjo un error durante el procedimiento de login, contacte un administrador\n[TRAZA]\n\t<ul>\n\t<li><strong>toba_autenticacion_saml_onelogin->verificar_errores_onelogin</strong><br />Archivo: /var/siu/arai-usuarios/2.2.5/vendor/siu-toba/framework/php/nucleo/lib/autenticacion/toba_autenticacion_saml_onelogin.php, l\xednea 217<br />Par\xe1metros: <ol><li>Instancia de <em>OneLogin_Saml2_Auth</em></li>\n\t</ol>\n\t</li>\n\t<li><strong>toba_autenticacion_saml_onelogin->verificar_acceso</strong><br />Archivo: /var/siu/arai-usuarios/2.2.5/gestion/php/login/ci_login.php, l\xednea 249<br />\t</li>\n\t<li><strong>ci_login->evt__cas__ingresar</strong><br />Archivo: /var/siu/arai-usuarios/2.2.5/gestion/php/login/ci_login.php, l\xednea 47<br />\t</li>\n\t<li><strong>ci_login->ini</strong><br />Archivo: /var/siu/arai-usuarios/2.2.5/vendor/siu-toba/framework/php/nucleo/componentes/interface/toba_ci.php, l\xednea 94<br />\t</li>\n\t<li><strong>toba_ci->inicializar</strong><br />Archivo: /var/siu/arai-usuario...SIGUE..., referer: https://idp-test.unx.edu.ar/module.php/arai/loginuserpass.php?

Esta situación partió de la actualización de onelogin/php-saml a la versión 2.17.0 en la cual cambian el default del parámetro a `strict=true`.
