### ISSUE TITLE
Incorporar Memcached para sesion

### ISSUE THREAD

**Issue by enfoqueNativo** [SIU-Toba/framework#59]
Incorporar Memcached para posibilitar escalamiento horizontal, ver si se puede levantar desde env variable y si es viable configurarlo en contexto_ejecucion. Seguro impacta en el manejador

**Comment by andres-blanco** [comment]
Porque sería en el contexto de ejecución? no se puede levantar directamente de la ENV?

**Comment by gpilla** [comment]
La sesión en Toba no esta totalmente delegada en PHP? Si es así lo que se debe configurar es la session en el php.ini
