### ISSUE TITLE
Mejorar comando autoload

### ISSUE THREAD

**Issue by enfoqueNativo** [SIU-Toba/framework#70]
Probar de usar [betterReflection](https://github.com/Roave/BetterReflection) para generar el autoload de los proyectos en Toba, quizas se pueda evitar el segfault en archivos brutoCodigoTodoEnUno

**Comment by sergiovier** [comment]
Seguro ya viste la nueva funcionalidad de [preload](https://stitcher.io/blog/preloading-in-php-74), hay que tenerlo en cuenta cosa de que esto no traiga problemas a futuro... no encontré nada en betterReflection aún.

**Comment by enfoqueNativo** [comment]
Me parece que son dos cosas distintas, lo mio apunta a encontrar una mejor forma de generar el autoload del proyecto que se buguea con archivos muy grandes y hay que tocarlo a mano.

El preloading (php 7.4+) es simplemente definir que clases deben ser cacheadas al inicio del webserver... algo mas parecido a lo que se puede hacer con memcached (sin el expire!) hoy.

Quizas haya que crear un comando aparte para ese caso, usando los logs del framework para determinar que subclases (del proyecto) son mas usadas (via los items ejecutados)... y que se pueda extender de alguna manera para incluir clases que el desarrollador sabe son centrales... el pre-loading da para issue aparte.

**Comment by enfoqueNativo** [comment]
Done [63be7234248268707fc39db86d67ace4960e564d]
