### ISSUE TITLE
RandomLib duplicado

### ISSUE THREAD

**Issue by sergiovier** [SIU-Toba/framework#75]
`Warning: Ambiguous class resolution, "RandomLib\Source\Sodium" was found in both "/usr/local/build/ui/vendor/ircmaxell/random-lib/lib/RandomLib/Source/Sodium.php" and "/usr/local/build/ui/vendor/paragonie/random-lib/lib/RandomLib/Source/Sodium.php", the first will be used.`

Posiblemente, duplicado con paragonie/random-lib e ircmaxell/random-lib.

**Comment by enfoqueNativo** [comment]
Actualizada la version de security-multitool para que coincidan los paquetes, aunque probablemente lo vuele y busque reemplazo. [42243b9f96111aece3997de94b79f003422c722e]
