### ISSUE TITLE
Docuementación de 'instalacion_silenciosa instalar --archivo_configuracion'

### ISSUE THREAD

**Issue by miguel9554** [SIU-Toba/framework#81]
Está documentado en algún lado el yaml que espera el instalador? Me refiero a qué keys espera, con qué tipo de valores y si tienen que estar estructurados de alguna manera particular.

**Comment by enfoqueNativo** [comment]
Hola Miguel, 

eso estaba en un repo que se llamaba template-proyecto-vacio que elimine el año pasado, pude rescatar una copia que tenia en disco, asi que subi esa infoy la copia del archivo  al repo [template-proyecto-toba](https://github.com/SIU-Toba/template-proyecto-toba) 

Hay algunos parametros extra que usa Toba pero que no son de mayor importancia en gral por lo que puede ir con los valores por defecto, los podria ir agregando a la estructura del archivo si es que son necesarios.. pero van a estar disponibles con un nuevo release de Toba recien.
