### ISSUE TITLE
Rango de años en componente calendario

### ISSUE THREAD

**Issue by rossinicolas** [SIU-Toba/framework#93]
Habría que extender el rango por defecto del componente ya que si no está personalizado en el proyecto, como debe ser en la mayoría de los casos, no se podrá visualizar mas allá de este mes.

protected $_rango_anios = array(2000, 2020);

**Comment by enfoqueNativo** [comment]
@rossinicolas Es el rango por defecto con el que se inicializa (que se puede revisar como tal), eso no quita que se pueda seguir visualizando sin problema alguno. No es necesario que el componente este personalizado, con efectuar una llamada a [esta](https://github.com/SIU-Toba/framework/blob/develop/php/nucleo/componentes/interface/toba_ei_calendario.php#L107) funcion se puede ajustar el rango de años directamente en la configuracion del componente en el Ci.

**Comment by enfoqueNativo** [comment]
Fixed @[fab2f5ba1586dafb344202c0ed1b31138a45101e]
