### ISSUE TITLE
No lee ENV de configuración WS Rest

### ISSUE THREAD

**Issue by sergiovier** [SIU-Toba/framework#94]
Al parecer, [acá](https://github.com/SIU-Toba/framework/blob/v3.3.15/php/nucleo/lib/toba_servicio_web_cliente_rest.php#L93) se intenta leer la ENV en la forma `CREDENCIALES_API_BASIC_rest_arai_usuarios`. 

Sólo en windows es case-insensitive el dichoso "getenv()"

**Comment by enfoqueNativo** [comment]
Buen catch!.. me pasa por no seguir mi propia documentacion
